export const EXERCISE = "exercise"
export const TRAIN_PROGRAM = "trainProgram"
export const TRAIN = "train"
export const EXERCISE_SET = "exerciseSet"
export const ACTIVE_TRAIN_PROGRAM = "activeTrainProgram"
